name = "Semifields"
uuid = "ce172cc3-0a93-45b0-a8c2-dc4561e814ec"
authors = ["Francisco J. Valverde <francisco.valverde@urjc.es>"]
version = "0.0.1"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
PkgDependency = "9eb5382b-762c-48ca-8139-e736883fe800"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
ChainRulesCore = "1.22.0"
LinearAlgebra = "1.10.0"
LogExpFunctions = "0.3.27"
PkgDependency = "0.5.0"
Reexport = "1.2.2"
julia = "1.10.1"
