name = "Semifields"
uuid = "ce172cc3-0a93-45b0-a8c2-dc4561e814ec"
authors = ["Francisco J. Valverde <francisco.valverde@urjc.es>"]
version = "0.0.1"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
Semirings = "900aad66-9ca5-44d4-b043-321c62cb7767"

[compat]
ChainRulesCore = "1.22.0"
LogExpFunctions = "0.3.27"
Semirings = "0.5.5"
julia = "1.10.1"
